-- Run as SYS on XEPDB1 (gvenzl/oracle-xe)
-- Example:
--   docker exec -i oracle-db sqlplus -s sys/YourPassword123@XEPDB1 as sysdba @/tmp/01_create_user.sql

ALTER SESSION SET CONTAINER = XEPDB1;

BEGIN
  FOR r IN (SELECT username FROM dba_users WHERE username = 'SHOP') LOOP
    EXECUTE IMMEDIATE 'DROP USER shop CASCADE';
  END LOOP;
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE USER shop IDENTIFIED BY ShopPassword123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO shop;
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO shop;

EXIT;
